########################################################################
#                       Target
########################################################################

TARGET_INSTALL_DIR	:=	..

PROGRAM_ppu		:= fixedgrid

IMPORTS			:= ../spu/lib_fixedgrid_spu.a

VPATH			:= ../common

LDFLAGS			:= -lspe2 -lpthread -lm

INCLUDE			:= -I../config

########################################################################
# make.footer
########################################################################
# make.footer is in the top of the SDK

include ../Makefile.defs
